zero/account/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from zero.account import views

urlpatterns = patterns('',
    url(r'^details$', views.details, name='account-details'),
    url(r'^transaction$', views.transaction, name='transaction-view'),
)

zero/company/urls.py
from django.conf.urls.defaults import *
from django.conf import settings
from zero.company import views

urlpatterns = patterns('',
    url(r'^api/list', views.api_list, name='api-company-list'),
    url(r'^api/ohlc/([\w\.:]*)/(\d*)$', views.api_ohlc, name='api-company-ohlc'),
    url(r'^api/indexes$', views.api_index_list, name='api-company-indexes'),
    url(r'^api/index/(.+)$', views.api_index, name='api-company-index'),
    url(r'^api/sectors$', views.api_sector_list, name='api-company-sectors'),
    url(r'^api/sector/(.+)$', views.api_sector, name='api-company-sector'),

    url(r'^$', views.list, name='company-list'),
    url(r'^indexes$', views.index_list, name='index-list'),
    url(r'^index/(.+)$', views.index, name='index'),
    url(r'^sectors$', views.sector_list, name='sector-list'),
    url(r'^sector/(.+)$', views.sector, name='sector'),
    url(r'^movers/(\d+)/(\d+)/(\d+)$', views.movers, name='company-movers'),
    url(r'^movers$', views.movers_today, name='company-movers-today'),
    url(r'^([\w\.:]*)$', views.details, name='company-details'),

)

zero/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', 'zero.views.home', name='home-view'),
    url(r'^company/', include('zero.company.urls')),
    url(r'^account/', include('zero.account.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    #(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_DOC_ROOT}),
)

zero/account/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from zero.company.models import Company, Price

class Account(models.Model):
    user    = models.ForeignKey(User, unique=True)
    balance = models.FloatField(default=0)

    def buy(self, company, quantity):
        price = company.latest_price();
        cost = quantity * price
        if self.balance < cost:
            return False
        try:
            asset = Asset.objects.get(company=company, user=self.user)
            asset.quantity = asset.quantity + quantity
        except:
            asset = Asset.objects.create(company=company, user=self.user, quantity=quantity)

        asset.save()
        self.balance = self.balance - cost
        self.save()
        date = datetime.now()
        transaction = Transaction.objects.create(company=company, quantity=quantity, user=self.user, date=date, category='buy', price=price)
        return True

    def sell(self, company, quantity):
        price = company.latest_price();
        try:
            asset = Asset.objects.get(company=company, user=self.user)
        except:
            return False
        if asset.quantity < quantity:
            quantity = asset.quantity
        asset.quantity = asset.quantity - quantity
        if asset.quantity == 0:
            asset.delete()
        else:
            asset.save()
        cost = quantity * price
        self.balance = self.balance + cost
        self.save()
        date = datetime.now()
        transaction = Transaction.objects.create(company=company, quantity=quantity, user=self.user, date=date, category='sell', price=price)
        return True

    def __unicode__(self):
        return '%s %s %s' % (self.user.email, self.user.first_name, self.user.last_name)

User.account = property(lambda u: Account.objects.get_or_create(user=u)[0])

class Asset(models.Model):
    company     = models.ForeignKey(Company)
    quantity    = models.FloatField(default=0)
    user        = models.ForeignKey(User)

    def value(self):
        price = Price.objects.order_by('-date').filter(company=self.company)[:1].get()
        return self.quantity * price.closed

    def __unicode__(self):
        return '%i x %s' % (self.quantity, self.company.symbol)

class Transaction(models.Model):

    CATEGORY_CHOICES = (
        ('buy', 'Buy'),
        ('sell', 'Sell'),
    )

    company     = models.ForeignKey(Company)
    quantity    = models.FloatField(default=0)
    user        = models.ForeignKey(User)
    date        = models.DateTimeField()
    category    = models.CharField(max_length=8, choices=CATEGORY_CHOICES)
    price       = models.FloatField(default=0)

    def value(self):
        return self.quantity * self.price

    def current_value(self):
        price = Price.objects.order_by('-date').filter(company=self.company)[:1].get()
        return self.quantity * price.closed

    def __unicode__(self):
        return '%i x %s @ %i = $%i (%s)' % (self.quantity, self.company.symbol, self.price, (self.quantity * self.price), self.date)

zero/company/models.py
from django.db import models
import string, random
import datetime
from time import mktime
from django.template.defaultfilters import slugify

class Sector(models.Model):
    id      = models.CharField(primary_key=True, max_length=8)
    name    = models.CharField(max_length=32)
    parent  = models.ForeignKey('self', null=True, blank=True, related_name='industries')

    def __unicode__(self):
        parent = self.parent
        ret = self.name
        if self.parent:
            return '%s > %s' % (self.parent.name, self.name)
        else:
            return self.name

class Company(models.Model):

    SECTOR_CHOICES = (
        ('ts', 'Telecommunications Services'),
        ('in', 'Industrials'),
        ('cd', 'Consumer Discretionary'),
        ('ut', 'Utilities'),
        ('cs', 'Consumer Staples'),
        ('hc', 'Health Care'),
        ('ma', 'Materials'),
        ('fi', 'Financials'),
        ('en', 'Energy'),
        ('it', 'Information Technology'),
    )

    symbol   = models.CharField(primary_key=True, max_length=16)
    name     = models.CharField(max_length=255)
    exchange = models.CharField(max_length=32)
    sector   = models.CharField(max_length=2, choices=SECTOR_CHOICES)
    location = models.CharField(max_length=255)

    def __unicode__(self):
        return "%s (%s)" % (self.name, self.symbol)

    def latest_price(self):
        price = Price.objects.order_by('-date').filter(company=self)[:1].get()
        return price

    def ohlc(self, days):
        prices = self.price_set.order_by('-date').all()[:days]
        results = []
        for i in prices:
            results.append([int(mktime(i.date.timetuple())), i.opened, i.high, i.low, i.closed])
        results.reverse()
        return results

    def google_url(self):
        return 'http://www.google.com/finance?q=%s:%s' % (self.exchange, self.symbol)

    def stats(self, days):
        prices = self.price_set.order_by('-date').all()[:days]
        closes = []
        start = 0
        end = 0
        high = 0
        low = 9999999
        for i in prices:
            if i.high > high:
                high = i.high
            if i.low < low:
                low = i.low
            closes.append(i.closed)
        closes.reverse()
        if low == 9999999:
            low = 0
        return { 'high': high, 'low': low, 'closed': closes, }

    def stats7(self):
        return self.stats(7)

    def stats14(self):
        return self.stats(14)

    def stats30(self):
        return self.stats(30)

    def stats60(self):
        return self.stats(60)

    def stats90(self):
        return self.stats(90)

class Price(models.Model):

    CATEGORY_CHOICES = (
        ('h', 'Hour'),
        ('d', 'Day'),
        ('m', 'Month'),
        ('y', 'Year'),
    )

    company     = models.ForeignKey('Company')
    category    = models.CharField(max_length=1, choices=CATEGORY_CHOICES)
    date        = models.DateTimeField()
    opened      = models.FloatField()
    high        = models.FloatField()
    low         = models.FloatField()
    closed      = models.FloatField()
    adj_closed  = models.FloatField()
    volume      = models.IntegerField()

class Index(models.Model):

    name = models.CharField(max_length=32)
    slug = models.CharField(max_length=32)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Index, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.name

class IndexCompany(models.Model):

    company = models.ForeignKey('Company')
    index = models.ForeignKey('Index')

    def __unicode__(self):
        return '%s (%s)' % (self.company.name, self.index.name)

zero/account/views.py
from django.template import Context, RequestContext
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render_to_response
from django.conf import settings
from zero.account.models import Account, Asset, Transaction
from zero.company.models import Company
from datetime import datetime
import json

def details(request):
    assets = Asset.objects.filter(user=request.user)
    transactions = Transaction.objects.filter(user=request.user).order_by('-date')
    return render_to_response('account/details.html', { 'assets': assets, 'transactions': transactions }, context_instance=RequestContext(request))

def transaction(request):
    symbol   = request.GET.get('symbol', False)
    quantity = int(request.GET.get('quantity', 0))
    category = request.GET.get('category', False)
    company = Company.objects.get(symbol=symbol)
    if category == 'buy':
        status = request.user.account.buy(company, quantity)
    elif category == 'sell':
        status = request.user.account.sell(company, quantity)
    return HttpResponse(json.dumps({ 'status': status }), mimetype='application/json')

zero/company/views.py
from django.template import Context, RequestContext
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render_to_response
from django.conf import settings
from zero.company.models import *
from json import dumps
from time import mktime
from datetime import date, timedelta

def list(request):
    company = Company.objects.all().order_by('name')
    return render_to_response('company/list.html', { 'list': company }, context_instance=RequestContext(request))

def api_list(request):
    callback   = request.GET.get('callback', False)
    company = Company.objects.all().order_by('name')
    response_data = []
    for i in company:
        response_data.append({ 'symbol': i.symbol, 'name': i.name, 'exchange': i.exchange, 'sector': i.sector, 'location': i.location })
    response_str = dumps(response_data);
    if callback:
        response_str = '%s(%s)' % (callback, response_str)
    return HttpResponse(response_str, mimetype="text/javascript")

def index_list(request):
    indexes = Index.objects.all()
    return render_to_response('company/indexes.html', { 'list': indexes }, context_instance=RequestContext(request))

def api_index_list(request):
    callback   = request.GET.get('callback', False)
    indexes = Index.objects.all()
    response_data = []
    for i in indexes:
        response_data.append({ 'name': i.name, 'slug': i.slug })
    response_str = dumps(response_data);
    if callback:
        response_str = '%s(%s)' % (callback, response_str)
    return HttpResponse(response_str, mimetype="text/javascript")

def index(request, slug):
    index = Index.objects.get(slug=slug)
    company = IndexCompany.objects.filter(index=index)
    l = []
    for i in company:
        l.append(i.company)
    return render_to_response('company/list.html', { 'list': l, 'index': index }, context_instance=RequestContext(request))

def api_index(request, slug):
    callback   = request.GET.get('callback', False)
    index = Index.objects.get(slug=slug)
    company = IndexCompany.objects.filter(index=index)
    response_data = []
    for i in company:
        response_data.append({ 'symbol': i.company.symbol, 'name': i.company.name, 'exchange': i.company.exchange, 'sector': i.company.sector, 'location': i.company.location })
    response_str = dumps(response_data);
    if callback:
        response_str = '%s(%s)' % (callback, response_str)
    return HttpResponse(response_str, mimetype="text/javascript")

def sector_list(request):
    sectors = Company.SECTOR_CHOICES
    return render_to_response('company/sectors.html', { 'list': sectors }, context_instance=RequestContext(request))

def api_sector_list(request):
    callback   = request.GET.get('callback', False)

    indexes = Index.objects.all()
    response_data = {}
    for i in Company.SECTOR_CHOICES:
        response_data[i[0]] = i[1]
    response_str = dumps(response_data);
    if callback:
        response_str = '%s(%s)' % (callback, response_str)
    return HttpResponse(response_str, mimetype="text/javascript")

def sector(request, sector):
    company = Company.objects.filter(sector=sector)
    return render_to_response('company/sector.html', { 'list': company, 'sector': sector }, context_instance=RequestContext(request))

def api_sector(request, sector):
    callback   = request.GET.get('callback', False)
    company = Company.objects.filter(sector=sector)
    response_data = []
    for i in company:
        response_data.append({ 'symbol': i.symbol, 'name': i.name, 'exchange': i.exchange, 'sector': i.sector, 'location': i.location })
    response_str = dumps(response_data);
    if callback:
        response_str = '%s(%s)' % (callback, response_str)
    return HttpResponse(response_str, mimetype="text/javascript")

def details(request, symbol):
    company = Company.objects.get(symbol=symbol)
    return render_to_response('company/details.html', { 'company': company }, context_instance=RequestContext(request))

def api_ohlc(request, symbol, days):
    callback   = request.GET.get('callback', False)
    company = Company.objects.get(symbol=symbol)
    response_data = company.ohlc(days)
    response_str = dumps(response_data);
    if callback:
        response_str = '%s(%s)' % (callback, response_str)
    return HttpResponse(response_str, mimetype="text/javascript")


def movers_today(request):
    today = datetime.date.today()
    return movers(request, today.year, today.month, today.day)

def movers(request, year, month, day):
    year = int(year)
    month = int(month)
    day = int(day)
    date = datetime.date(year, month, day)
    dates = []
    oneday = datetime.timedelta(1)

    for i in range(-5,5):
        dates.append(date + (oneday * i))
    dates.reverse()

    prices = Price.objects.filter(date=date)
    p = []
    for i in prices:
        p.append({ 'company': i.company, 'opened': i.opened, 'high': i.high, 'low': i.low, 'closed': i.closed, 'change': round(i.closed - i.opened, 2), 'change_pct': round(((i.closed - i.opened)/i.opened) * 100,2) })
    return render_to_response('company/movers.html', { 'date': date, 'prices': p, 'dates': dates }, context_instance=RequestContext(request))

zero/views.py
from django.template import Context, RequestContext
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden
from django.shortcuts import render_to_response
from django.conf import settings

def home(request):
    return render_to_response('home.html', {}, context_instance=RequestContext(request))

zero/templates/company/details.html
{% extends "base.html" %}
{% block page_title %}
    <div class="hero-unit">
        <div class="row">
            <div class="span3">
                <div class="company-price">${{ company.latest_price.closed }}</div>
                <div class="company-date"><a href="{% url 'company-movers' company.latest_price.date.year company.latest_price.date.month company.latest_price.date.day %}" class="company-movers">{{ company.latest_price.date|date:"Y-m-d" }}</a></div>
            </div>
            <div class="span3">
                <div class="company-name">{{ company.name }}</div>
                <div class="company-symbol"><a href="{{ company.google_url }}">{{ company.exchange }}:{{ company.symbol }}</a></div>
            </div>
            <div class="span3">
                <div class="company-location">{{ company.location }}</div>
                <div class="company-sector">{{ company.get_sector_display }}</div>
            </div>
        </div>
    </div>
{% endblock page_title %}
{% block content %}
    <style type="text/css">
        .company-header {
            padding: 50px 20px 20px 20px;
            overflow: hidden;
            background-color: #EEE;
        }
        .company-header .left-col {
            float: left;
            margin-right: 30px;
        }
        .company-header .right-col {
            float: left;
            margin-right: 30px;
        }
        .company-header .mid-col {
            float: left;

            margin-right: 30px;
        }
        .company-name {
            font-size: 24px;
            font-weight: bold;
        }
        .company-symbol {
            font-size: 12px;
            color: #999;
            font-weight: normal;
        }
        .company-location {
            font-size: 11px;
        }
        .company-sector {
            font-size: 11px;
        }
        .company-price {
            font-size: 24px;
            font-weight: bold;
        }
        .company-date {
            
        }
        .company-date .company-movers:link,
        .company-date .company-movers:visited {
            text-decoration: none;
            color: #999;
        }
    </style>


    <div id="stock-chart"></div>
    <div id="tweet-chart"></div>

<script type="text/javascript">
    $.ajax({
        url: '/company/api/ohlc/{{ company.symbol }}/99999?callback=?',
        dataType: 'json',
        success: function(data) {
            for (var i = 0, il = data.length; i < il; i++) {
                data[i][0] = data[i][0] * 1000;
            }
            window.chart = new Highcharts.StockChart({
                chart : { renderTo : 'stock-chart' },
                rangeSelector : { selected : 1 },
                series : [{
                    name : '{{ company.symbol }}',
                    data : data,
                    tooltip: { valueDecimals: 2 }
                }]
            });
        }
    });


    $.ajax({ 
        url: 'http://otter.topsy.com/searchhistogram.js?q=${{ company.symbol }}&period=90&callback=?',
        dataType: 'json',
        success: function(data) {
            var cat_map = {};
            var points = $.extend([],data.response.histogram);
            var oneday = 60 * 60 * 24 * 1000;
            var current = new Date().getTime();
            console.log('current: ' + (new Date()));
            var categories = []
            points.reverse();
            for (var i = 0, il = points.length; i < il; i++) {
                var date = new Date(current - (oneday * i));
                var str = (date.getMonth() + 1) + '/' + date.getDate();
                cat_map[str] = date;
                categories.push(str);
            }
            categories.reverse();
            var chart = new Highcharts.Chart({
                chart: {
                    renderTo: 'tweet-chart',
                    type: 'line',
                    marginRight: 130,
                    marginBottom: 25
                },
                xAxis: {
                    categories: categories,
                    labels: {
                        step: 7
                    }
                },
                yAxis: {
                    title: { text: 'Mentions' },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                title: { 
                    text: 'Mentions for ${{ company.symbol }}'
                },
                tooltip: {
                    formatter: function() { return '<b>'+ this.series.name +'</b><br/>'+ this.x +': '+ this.y +' Mentions'; }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                plotOptions: {
                    series: {
                        cursor: 'pointer',
                        point: {
                            events: {
                                click: function() {
                                    var q = this.series.name;
                                    var date = cat_map[this.category];
                                    console.log(date);
                                    var ts = Math.round(date/1000) - (60*60*24);
                                    var url = 'http://topsy.com/s?q=' + encodeURIComponent(q) + '&mintime=' + ts;
                                    window.open(url,'_blank');
                                    return;

                                    
                                    hs.htmlExpand(null, {
                                        pageOrigin: { x: this.pageX, y: this.pageY },
                                        headingText: this.series.name,
                                        maincontentText: Highcharts.dateFormat('%A, %b %e, %Y', this.x) +':<br/> '+ this.y +' visits',
                                        width: 200
                                    });
                                }
                            }
                        },
                        marker: {
                            lineWidth: 1
                        }
                    }
                },
                series: [{
                    name: '${{ company.symbol }}',
                    data: points
                }]
            });

        }
    });

    
</script>
{% endblock %}

zero/templates/company/indexes.html
{% extends "base.html" %}
{% load number_extras %}
{% block head %}{% endblock head %}
{% block page_title %}
    <div class="hero-unit">
        <h2>Indexes</h2>
    </div>
{% endblock page_title %}
{% block content %}

{% for i in list %}
    <a href="{% url 'index' i.slug %}">{{ i.name }}</a><br/>
{% endfor %}
{% endblock content %}

zero/templates/company/list.html
{% extends "base.html" %}
{% load number_extras %}
{% block head %}{% endblock head %}
{% block page_title %}
    <div class="hero-unit">
        <h2>{{ index.name }}</h2>
    </div>
{% endblock page_title %}
{% block content %}
<div class="navbar">
    <div class="navbar-inner">
        <div class="navbar-form">
            <select id="days">
                <option value="7">7 Days</option>
                <option value="14">14 Days</option>
                <option value="30" selected="selected">30 Days</option>
                <option value="60">60 Days</option>
                <option value="90">90 Days</option>
            </select>
            <button class="btn" id="go">Go</button>
        </div>
    </div>
</div>
<div id="company-view"></div>
<script type="text/javascript">
var index = { 'name': '{{ index.name }}', 'slug': '{{ index.slug }}' };
$(document).ready(function() {
    Zero.api({ 
        url: '/company/api/list',
        data: { index: index.slug },
        callback: function(data) { 
            console.log(data); 
            var table_html = [
                '<table class="table table-striped" id="company-list">',
                    '<thead>',
                    '<tr>',
                        '<th><span class="sorter"></span>Symbol</th>',
                        '<th><span class="sorter"></span>Name</th>',
                        '<th><span class="sorter"></span>Sector</th>',
                        '<th><span class="sorter"></span>Past 30 Days</th>',
                        '<th class="number"><span class="sorter"></span>Current</th>',
                        '<th class="number"><span class="sorter"></span>High</th>',
                        '<th class="number"><span class="sorter"></span>High %</th>',
                        '<th class="number"><span class="sorter"></span>Low</th>',
                        '<th class="number"><span class="sorter"></span>Low %</th>',
                        '<th class="number"><span class="sorter"></span>Oldest</th>',
                        '<th class="number"><span class="sorter"></span>Overall</th>',
                        '<th class="number"><span class="sorter"></span>Overall %</th>',
                    '</tr>',
                    '</thead>',
                    '<tbody></tbody>',
                '</table>'
            ];
            var view = $('#company-view');
            var table = $(table_html.join(''));
            var tbody = table.find('tbody');
            view.append(table);

            for (var i = 0, il = data.length; i < il; i++) {
                var html = [
                    '<tr data-symbol="' + data[i].symbol + '" class="' + (i % 2 ? 'odd' : 'even') + '">',
                        '<td class="symbol-col"><a href="/company/' + data[i].symbol + '">' + data[i].symbol + '</a></td>',
                        '<td class="name-col">' + data[i].name  + '</td>',
                        '<td class="sector-col">' + Zero.sector(data[i].sector)  + '</td>',
                        '<td class="chart-col"></td>',
                        '<td class="number oldest-col"></td>',
                        '<td class="number high-col"></td>',
                        '<td class="number high-pct-col"></td>',
                        '<td class="number low-col"></td>',
                        '<td class="number low-pct-col"></td>',
                        '<td class="number current-col"></td>',
                        '<td class="number overall-col"></td>',
                        '<td class="number overall-pct-col"></td>',
                    '</tr>'
                ].join('');
                tbody.append(html);
            }
            table.tablesorter();
            table.trigger('update');
            table.bind('sortEnd', function() {
                var rows = $(this).find('tbody tr');
                rows.removeClass('odd').removeClass('even');
                rows.each(function(idx, i) { $(i).addClass(idx % 2 ? 'even' : 'odd'); });
            });
        }
    });
});
$('#days').change(function() {
    load_stats({ days: $(this).val() });
});
$('#go').click(function() {
    load_stats({ days: $('#days').val() });
});
function load_stats(options) {
    var rows = $('tr[data-symbol]')
    rows.each(function(idx, i) {
        var $this = $(i);
        var symbol = $this.data('symbol');
        var days = options.days;
        $.ajax({
            url: '/company/api/ohlc/' + symbol + '/' + days + '?callback=?',
            dataType: 'json',
            success: function(data) {
                var chart_col =     $this.find('.chart-col').empty(),
                    current_col =   $this.find('.current-col').empty(),
                    high_col =      $this.find('.high-col').empty(),
                    high_pct_col =  $this.find('.high-pct-col').empty(),
                    low_col =       $this.find('.low-col').empty(),
                    low_pct_col =   $this.find('.low-pct-col').empty(),
                    oldest_col =    $this.find('.oldest-col').empty(),
                    overall_col =   $this.find('.overall-col').empty();
                    overall_pct_col = $this.find('.overall-pct-col').empty();

                var stats = Zero.ohlc_stats(data);
                console.log(stats);
                rickshaw_values = [];
                for (var i = 0, il = stats.ohlc.length; i < il; i++) {
                    rickshaw_values.push({ x: i, y: stats.ohlc[i].close - stats.low });
                }
                var rs = $('<div/>', { 'class': 'sp-' + symbol, style: 'width:300px; height: 32px' }).appendTo(chart_col);
                var graph = new Rickshaw.Graph({
                    element: document.querySelector('.sp-' + symbol),
                    renderer: 'bar',
                    series: [{ data: rickshaw_values, color: 'steelblue' }]
                });
                graph.render();
                $this.data('stats', data);
                current_col     .html('$' + stats.current);
                high_col        .addClass(Zero.number_class(stats.high_diff))       .html('$' + stats.high);
                high_pct_col    .addClass(Zero.number_class(stats.high_diff))       .html(stats.high_diff_pct + '%');
                low_col         .addClass(Zero.number_class(stats.low_diff))        .html('$' + stats.low);
                low_pct_col     .addClass(Zero.number_class(stats.low_diff))        .html(stats.low_diff_pct + '%');
                oldest_col      .addClass(Zero.number_class(stats.oldest_diff)) .html('$' + stats.oldest);
                overall_col     .addClass(Zero.number_class(stats.oldest_diff)) .html('$' + stats.oldest_diff);
                overall_pct_col .addClass(Zero.number_class(stats.oldest_diff_pct)) .html(stats.oldest_diff_pct + '%');
    
                if (rows[idx] === rows[rows.length - 1] || idx % 10 === 0) {
                    $('table').trigger('update');
                }
            }
        });
    });
}
</script>
{% endblock content %}

zero/templates/company/sectors.html
{% extends "base.html" %}
{% load number_extras %}
{% block head %}{% endblock head %}
{% block page_title %}
    <div class="hero-unit">
        <h2>Sectors</h2>
    </div>
{% endblock page_title %}
{% block content %}

{% for i in list %}
    <a href="{% url 'sector' i.0 %}">{{ i.1 }}</a><br/>
{% endfor %}
{% endblock content %}